### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by markaslett** [drbrain/indigo-powerview#1]
drbrain,

I just setup my new Powerview Huib 2 and I am geeting a lot of error messages. Also, although the scenes import I cannot successfully trigger them. Controlling the shades from the iphone app works fine. 

Thanks, Mark
__________

May 22, 2018 at 5:53:03 AM
   Error                           process (pid 26896) failed to quit after polite request -- forcing it to quit now
   Stopped plugin "PowerView 1.0.0"
   NEST Home                       Basement MA Thermostat  last_connection updated to 2018-05-22T09:52:12.296Z
   NEST Home                       Master Bedroom Thermostat  last_connection updated to 2018-05-22T09:52:10.382Z
   Trigger                         isNestMA_MasterBedroom_Temp
   NEST Home                       Master Bedroom Thermostat  ambient_temperature_f updated to 68
   Enabling plugin "PowerView 1.0.0"
   Starting plugin "PowerView 1.0.0" (pid 26917)
   Started plugin "PowerView 1.0.0"
   Schedule                        Master Bathroom Shower Lights Timer 1 (delayed action)
   Schedule                        Master Bathroom Shower Lights Timer (delayed action)
   Sent INSTEON                    "Master Bathroom Shower Lights" off
   Sent INSTEON                    "Master Bathroom Shower Lights" off
   NEST Home 3                     Bedroom VT Thermostat (Master Bedroom VT)  is_online updated to False
   PowerView Debug                 Discovering shades on 192.168.1.250
   PowerView Debug                 Creating shade 192.168.1.250:41390
   PowerView Debug                 Creating shade 192.168.1.250:41390
   PowerView Debug                 Creating shade 192.168.1.250:55699
   PowerView Debug                 Creating shade 192.168.1.250:55699
   PowerView Debug                 Creating shade 192.168.1.250:33058
   PowerView Debug                 Creating shade 192.168.1.250:33058
   PowerView Debug                 Creating shade 192.168.1.250:33633
   PowerView Debug                 Creating shade 192.168.1.250:33633
   PowerView Debug                 Creating shade 192.168.1.250:34428
   PowerView Debug                 Creating shade 192.168.1.250:34428
   PowerView Debug                 Creating shade 192.168.1.250:4532
   PowerView Debug                 Creating shade 192.168.1.250:4532
   PowerView Debug                 Creating shade 192.168.1.250:34294
   PowerView Debug                 Creating shade 192.168.1.250:34294
   PowerView Debug                 Creating shade 192.168.1.250:48540
   PowerView Debug                 Creating shade 192.168.1.250:48540
   PowerView Debug                 Creating shade 192.168.1.250:33623
   PowerView Debug                 Creating shade 192.168.1.250:33623
   PowerView Debug                 Creating shade 192.168.1.250:5056
   PowerView Debug                 Creating shade 192.168.1.250:5056
   PowerView Debug                 Updating shade 192.168.1.250:41390
   Error                           device "Den Rear Shade" state key signalStrength not defined (ignoring update request)
   PowerView Error                 Error in plugin execution ServerAddedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1136, in deviceCreated
  File "plugin.py", line 39, in deviceStartComm
  File "plugin.py", line 59, in update
  File "plugin.py", line 73, in updateShade
TypeError: state value type must be bool, int, real, or string

   PowerView Debug                 Updating shade 192.168.1.250:55699
   Error                           device "Den Side Shade" state key signalStrength not defined (ignoring update request)
   PowerView Error                 Error in plugin execution ServerAddedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1136, in deviceCreated
  File "plugin.py", line 39, in deviceStartComm
  File "plugin.py", line 59, in update
  File "plugin.py", line 73, in updateShade
TypeError: state value type must be bool, int, real, or string

   PowerView Debug                 Updating shade 192.168.1.250:33058
   Error                           device "Family Room Right Shade" state key signalStrength not defined (ignoring update request)
   PowerView Error                 Error in plugin execution ServerAddedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1136, in deviceCreated
  File "plugin.py", line 39, in deviceStartComm
  File "plugin.py", line 59, in update
  File "plugin.py", line 73, in updateShade
TypeError: state value type must be bool, int, real, or string

   PowerView Debug                 Updating shade 192.168.1.250:33633
   Error                           device "Kitchen Shade" state key signalStrength not defined (ignoring update request)
   PowerView Error                 Error in plugin execution ServerAddedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1136, in deviceCreated
  File "plugin.py", line 39, in deviceStartComm
  File "plugin.py", line 59, in update
  File "plugin.py", line 73, in updateShade
TypeError: state value type must be bool, int, real, or string

   PowerView Debug                 Updating shade 192.168.1.250:34428
   Error                           device "Dining Room Left Shade" state key signalStrength not defined (ignoring update request)
   PowerView Error                 Error in plugin execution ServerAddedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1136, in deviceCreated
  File "plugin.py", line 39, in deviceStartComm
  File "plugin.py", line 59, in update
  File "plugin.py", line 73, in updateShade
TypeError: state value type must be bool, int, real, or string

   PowerView Debug                 Updating shade 192.168.1.250:4532
   Error                           device "Dining Room Right Shade" state key signalStrength not defined (ignoring update request)
   PowerView Error                 Error in plugin execution ServerAddedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1136, in deviceCreated
  File "plugin.py", line 39, in deviceStartComm
  File "plugin.py", line 59, in update
  File "plugin.py", line 73, in updateShade
TypeError: state value type must be bool, int, real, or string

   PowerView Debug                 Updating shade 192.168.1.250:34294
   Error                           device "Dining Room Center Shade" state key signalStrength not defined (ignoring update request)
   PowerView Error                 Error in plugin execution ServerAddedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1136, in deviceCreated
  File "plugin.py", line 39, in deviceStartComm
  File "plugin.py", line 59, in update
  File "plugin.py", line 73, in updateShade
TypeError: state value type must be bool, int, real, or string

   PowerView Debug                 Updating shade 192.168.1.250:48540
   PowerView Error                 Error in plugin execution ServerAddedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1136, in deviceCreated
  File "plugin.py", line 39, in deviceStartComm
  File "plugin.py", line 59, in update
  File "plugin.py", line 73, in updateShade
TypeError: state value type must be bool, int, real, or string

   PowerView Debug                 Updating shade 192.168.1.250:33623
   Error                           device "Family Room Left Shade" state key signalStrength not defined (ignoring update request)
   PowerView Error                 Error in plugin execution ServerAddedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1136, in deviceCreated
  File "plugin.py", line 39, in deviceStartComm
  File "plugin.py", line 59, in update
  File "plugin.py", line 73, in updateShade
TypeError: state value type must be bool, int, real, or string

   PowerView Debug                 Updating shade 192.168.1.250:5056
   PowerView Error                 Error in plugin execution ServerAddedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1136, in deviceCreated
  File "plugin.py", line 39, in deviceStartComm
  File "plugin.py", line 59, in update
  File "plugin.py", line 73, in updateShade
TypeError: state value type must be bool, int, real, or string

**Comment by drbrain** [comment]
Reports are that #4 fixes the problem, will release Real Soon Now
