### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by markaslett** [drbrain/indigo-powerview#3]
drbrain,

so there is some communication. I can jog and calibrate the shades through indigo but the imported scenes do not trigger the blinds when the action is executed.

Thanks, Mark

**Comment by codeskein** [comment]
I've also been using the plugin with a gen 2 PowerView hub.

I've submitted pull request #4 which should fix the error messages you've reported as well as making the scene activation work.

**Comment by markaslett** [comment]
Codeskin, i must have missed this. Is there a new version to fix the Gen2 hub issue you mentioned. Many thanks, Mark

**Comment by codeskein** [comment]
I've submitted the change for consideration, but @drbrain needs to approve and merge it to create the new version.

**Comment by markaslett** [comment]
ok Thanks. Hope @drbrain is able to approve it soon ;o)

**Comment by stevebadger** [comment]
Hi Codeskein and Dr Brain, 

I too have the same issues with the plugin as markaslett, I have a hub with firmware 2.0.1037. I can see and pull the scenes from the hub into the plugin, but when an action to execute the scenes is made, nothing happens with the blinds here is the log : 


Error (client)                  timeout waiting for plugin response from net.segment7.powerview for request UiAction
   Error (client)                  timeout waiting for plugin response from net.segment7.powerview for request UiValidate
   Error (client)                  timeout waiting for plugin response from net.segment7.powerview for request UiClosed2
   Error (client)                  timeout waiting for plugin response from net.segment7.powerview for request UiGetValues2
   Error (client)                  timeout waiting for plugin response from net.segment7.powerview for request CallPluginFunc
   Error (client)                  runDialogForDevice() caught exception: NSInvalidArgumentException -- *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

19 Nov 2020 at 14:46:10
   Fantastic Weather Error         Unable to reach Dark Sky. Retrying in 50 seconds.
   Error (client)                  received unexpected packet response UiAction (waiting for UiGetValues2)
   Error (client)                  received unexpected packet response UiValidate (waiting for UiGetValues2)
   Error (client)                  received unexpected packet response UiClosed2 (waiting for UiGetValues2)
   Error (client)                  received unexpected packet response UiGetValues2 (waiting for )
   Error (client)                  received unexpected packet response CallPluginFunc (waiting for )

and then 

PowerView Error                 Error in plugin execution UiAction:

Traceback (most recent call last):
  File "plugin.py", line 50, in discoverShades
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/PowerView.indigoPlugin/Contents/Server Plugin/powerview.py", line 110, in shades
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/PowerView.indigoPlugin/Contents/Server Plugin/powerview.py", line 116, in __GET
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
URLError: <urlopen error [Errno 60] Operation timed out>

Can you help ? 
Best 
Steve
